import { test, expect, type Browser } from '@playwright/test'
import path from 'path'

/**
 * E2E Smoke Tests: adaptive dashboards
 *
 * Authenticated tests use the opt-in storage state generated by:
 * `pnpm exec playwright codegen --save-storage=src/test/e2e/auth.json`.
 * They remain gracefully skipped where no safe test account is configured.
 */
const AUTH_STATE_PATH = path.join(__dirname, 'auth.json')

async function authenticatedPage(browser: Browser) {
  try {
    const context = await browser.newContext({ storageState: AUTH_STATE_PATH })
    return { context, page: await context.newPage() }
  } catch {
    return null
  }
}

test.describe('Adaptive dashboard smoke tests (authenticated)', () => {
  test('authenticated user reaches an adaptive dashboard without a crash', async ({ browser }) => {
    const authenticated = await authenticatedPage(browser)
    if (!authenticated) {
      test.skip()
      return
    }

    const { context, page } = authenticated
    await page.goto('/app/dashboard')
    await expect(page).not.toHaveURL(/\/login/)
    await expect(page.locator('body')).not.toContainText('Application error')
    await expect(page.locator('body')).not.toContainText('Unhandled Runtime Error')
    await expect(page.locator('[data-dashboard-id]')).toHaveCount(1)
    await context.close()
  })

  test('edit mode exposes personalization controls without moving content accidentally', async ({ browser }) => {
    const authenticated = await authenticatedPage(browser)
    if (!authenticated) {
      test.skip()
      return
    }

    const { context, page } = authenticated
    await page.goto('/app/dashboard')
    const edit = page.getByRole('button', { name: 'Edit dashboard' })
    await expect(edit).toBeVisible()

    // Normal mode has no visible move handles.
    await expect(page.getByRole('button', { name: /Move .+ Use arrow keys or drag/ })).toHaveCount(0)
    await edit.click()

    await expect(page.getByRole('button', { name: 'Done' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Balanced' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Focus' })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Overview' })).toBeVisible()
    await expect(page.getByRole('button', { name: /Add tiles/ })).toBeVisible()
    await expect(page.getByRole('button', { name: 'Reset' })).toBeVisible()
    await expect(page.getByRole('button', { name: /Move .+ Use arrow keys or drag/ }).first()).toBeVisible()

    await page.getByRole('button', { name: 'Done' }).click()
    await expect(page.getByRole('button', { name: 'Edit dashboard' })).toBeVisible()
    await context.close()
  })

  test('desktop split is keyboard accessible', async ({ browser }) => {
    const authenticated = await authenticatedPage(browser)
    if (!authenticated) {
      test.skip()
      return
    }

    const { context, page } = authenticated
    await page.goto('/app/dashboard')
    const separator = page.getByRole('separator', { name: 'Resize columns' })
    await expect(separator).toBeVisible()
    const before = Number(await separator.getAttribute('aria-valuenow'))
    await separator.focus()
    await page.keyboard.press('ArrowLeft')
    await expect(separator).toHaveAttribute('aria-valuenow', String(before - 2))
    await context.close()
  })
})

test.describe('Dashboard unauthenticated guard', () => {
  test('/app/dashboard without session redirects to /login', async ({ page }) => {
    await page.goto('/app/dashboard')
    await expect(page).toHaveURL(/\/login/)
  })
})
