-- ============================================================
-- MIGRATION 00087: SEED BASELINE ONCOLOGY CONFERENCES
--
-- The AI discovery job remains the broad refresh mechanism, but production
-- should not launch with an empty Conferences space before the first successful
-- discovery sweep. Seed a small, high-confidence baseline of major oncology
-- meetings in the next 12 months.
-- ============================================================

insert into public.conferences (
  name,
  organizer,
  region,
  location,
  main_focus,
  topics,
  format,
  start_date,
  end_date,
  website_url,
  source_url,
  summary,
  relevance,
  dedupe_key
) values
  (
    'IASLC 2026 World Conference on Lung Cancer',
    'International Association for the Study of Lung Cancer',
    'asia_pacific',
    'Seoul, Republic of Korea',
    'Thoracic oncology',
    array['Lung cancer', 'Thoracic oncology', 'Patient advocacy'],
    'in_person',
    '2026-09-12',
    '2026-09-15',
    'https://wclc.iaslc.org/',
    'https://wclc.iaslc.org/',
    'Global lung cancer and thoracic oncology meeting with clinicians, researchers, nurses, and advocates.',
    92,
    'iaslc-2026-world-conference-on-lung-cancer:2026-09'
  ),
  (
    'ESMO Congress 2026',
    'European Society for Medical Oncology',
    'europe',
    'Madrid, Spain',
    'General oncology',
    array['Medical oncology', 'Cancer research', 'Clinical practice'],
    'in_person',
    '2026-10-23',
    '2026-10-27',
    'https://www.esmo.org/meeting-calendar/esmo-congress-2026',
    'https://www.esmo.org/meeting-calendar/esmo-congress-2026',
    'Major European and global oncology congress covering clinical cancer research, treatment, and patient care.',
    96,
    'esmo-congress-2026:2026-10'
  ),
  (
    'ESMO Asia Congress 2026',
    'European Society for Medical Oncology',
    'asia_pacific',
    'Singapore',
    'General oncology',
    array['Medical oncology', 'Asia-Pacific oncology', 'Clinical practice'],
    'in_person',
    '2026-12-04',
    '2026-12-06',
    'https://www.esmo.org/meeting-calendar/esmo-asia-congress-2026',
    'https://www.esmo.org/meeting-calendar/esmo-asia-congress-2026',
    'Regional ESMO congress bringing together oncology professionals across Asia-Pacific and beyond.',
    90,
    'esmo-asia-congress-2026:2026-12'
  ),
  (
    'San Antonio Breast Cancer Symposium 2026',
    'San Antonio Breast Cancer Symposium',
    'north_america',
    'San Antonio, Texas, United States',
    'Breast cancer',
    array['Breast cancer', 'Translational research', 'Clinical trials'],
    'in_person',
    '2026-12-08',
    '2026-12-11',
    'https://sabcs.org/',
    'https://sabcs.org/key-dates/',
    'Large international breast cancer research symposium with clinical, translational, and advocacy relevance.',
    94,
    'san-antonio-breast-cancer-symposium-2026:2026-12'
  ),
  (
    'ESMO Immuno-Oncology and Advanced Therapies Congress 2026',
    'European Society for Medical Oncology',
    'europe',
    'London, United Kingdom and online',
    'Immuno-oncology',
    array['Immuno-oncology', 'Advanced therapies', 'Biomarkers'],
    'hybrid',
    '2026-12-14',
    '2026-12-16',
    'https://www.esmo.org/meeting-calendar/esmo-immuno-oncology-advanced-therapies-congress-2026',
    'https://www.esmo.org/meeting-calendar/esmo-immuno-oncology-advanced-therapies-congress-2026',
    'Focused ESMO meeting on immuno-oncology and advanced therapies, available onsite and online.',
    89,
    'esmo-immuno-oncology-and-advanced-therapies-congress-2026:2026-12'
  ),
  (
    '20th St. Gallen International Breast Cancer Conference 2027',
    'St. Gallen Breast Cancer Conference',
    'europe',
    'Vienna, Austria',
    'Breast cancer',
    array['Breast cancer', 'Consensus guidance', 'Clinical practice'],
    'in_person',
    '2027-03-17',
    '2027-03-20',
    'https://www.sg-bcc.org/',
    'https://www.sg-bcc.org/',
    'International breast cancer conference known for consensus-oriented clinical discussion and guidance.',
    88,
    '20th-st-gallen-international-breast-cancer-conference-2027:2027-03'
  ),
  (
    'AACR Annual Meeting 2027',
    'American Association for Cancer Research',
    'north_america',
    'Orlando, Florida, United States',
    'Cancer research',
    array['Cancer biology', 'Translational research', 'Survivorship'],
    'in_person',
    '2027-04-02',
    '2027-04-07',
    'https://www.aacr.org/meeting/aacr-annual-meeting-2027/',
    'https://www.aacr.org/professionals/meetings/future-annual-meetings/',
    'Major cancer research meeting spanning population science, cancer biology, translational studies, and survivorship.',
    95,
    'aacr-annual-meeting-2027:2027-04'
  ),
  (
    'ESMO Breast Cancer 2027',
    'European Society for Medical Oncology',
    'europe',
    'Milan, Italy',
    'Breast cancer',
    array['Breast cancer', 'Clinical oncology', 'Patient care'],
    'hybrid',
    '2027-05-12',
    '2027-05-14',
    'https://www.esmo.org/meeting-calendar/esmo-breast-cancer-2027',
    'https://www.esmo.org/meeting-calendar/esmo-breast-cancer-2027',
    'ESMO meeting dedicated to advancing breast cancer patient care worldwide.',
    90,
    'esmo-breast-cancer-2027:2027-05'
  ),
  (
    'ASCO Annual Meeting 2027',
    'American Society of Clinical Oncology',
    'north_america',
    'Chicago, Illinois, United States and online',
    'General oncology',
    array['Clinical oncology', 'Cancer care', 'Patient advocacy'],
    'hybrid',
    '2027-06-04',
    '2027-06-08',
    'https://www.asco.org/annual-meeting',
    'https://www.asco.org/annual-meeting/dates-know',
    'Flagship ASCO oncology meeting covering cancer care, clinical science, and practice-changing research.',
    98,
    'asco-annual-meeting-2027:2027-06'
  )
on conflict (dedupe_key) do update set
  name = excluded.name,
  organizer = excluded.organizer,
  region = excluded.region,
  location = excluded.location,
  main_focus = excluded.main_focus,
  topics = excluded.topics,
  format = excluded.format,
  start_date = excluded.start_date,
  end_date = excluded.end_date,
  website_url = excluded.website_url,
  source_url = excluded.source_url,
  summary = excluded.summary,
  relevance = excluded.relevance,
  updated_at = now();
